language: cpp
#language: objective-c

notifications:
  email: false

os:
  - osx
  
before_install:
  - brew update
  - brew install qt
  - export QTDIR=$(brew info --json=v1 qt | jq -r '.[0].bottle.stable.cellar + "/" + .[0].name + "/" + .[0].installed[0].version')
  - export PATH=$PATH:$QTDIR/bin
  - export VERSION=`cat Software/VERSION`
  - qmake -v

script:
  - cd Software
  - set -e
  - ./update_locales.sh
  - qmake -r
  - make
  - macdeployqt bin/Prismatik.app -dmg
  - ls bin
  - hdiutil attach bin/Prismatik.dmg
  - ls /Volumes/bin:Prismatik/Prismatik.app
  - otool -L /Volumes/bin:Prismatik/Prismatik.app/Contents/MacOS/Prismatik
  - otool -L /Volumes/bin:Prismatik/Prismatik.app/Contents/Frameworks/QtWidgets.framework/Versions/5/QtWidgets
  - hdiutil detach /dev/disk1s1
  - curl -T bin/Prismatik.dmg "https://psieg.de/lightpack/osx_builds/Prismatik_${VERSION}_${TRAVIS_BUILD_NUMBER}.dmg" -u "${PSIEG_UPLOAD_USER}:${PSIEG_UPLOAD_PASSWORD}"
  - set +e
